=== ZeekoZhu/devstream-website/contributor-info/contributors.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/contributors.schema.json",
  "title": "Contributors",
  "description": "DevStream Contributors",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "email": {
        "type": "string"
      },
      "avatar": {
        "type": "string"
      },
      "certificationLink": {
        "type": "string"
      },
      "dateAdded": {
        "type": "string"
      },
      "badge": {
        "$ref": "badge-type.schema.json"
      }
    },
    "required": [
      "name",
      "email",
      "avatar",
      "dateAdded",
      "certificationLink",
      "badge"
    ]
  }
}

=== ZeekoZhu/devstream-website/contributor-info/contributors.json
[
  {
    "name": "alice",
    "email": "alice@example.com",
    "avatar": "https://loremflickr.com/200/200",
    "certificationLink": "https://www.credly.com/organizations/devstream/badge",
    "badge": {
      "type": "Evangelist",
      "achievement": "Associate"
    },
    "dateAdded": "2022/03/01"
  },
  {
    "name": "bob",
    "email": "bob@example.com",
    "avatar": "https://loremflickr.com/200/200",
    "certificationLink": "https://www.credly.com/organizations/devstream/badge",
    "badge": {
      "type": "Open-Source Contributor",
      "achievement": "Associate"
    },
    "dateAdded": "2022/03/01"
  },
  {
    "name": "cindy",
    "email": "cindy@example.com",
    "avatar": "https://loremflickr.com/200/200",
    "certificationLink": "https://www.credly.com/organizations/devstream/badge",
    "badge": {
      "type": "Evangelist",
      "achievement": "Associate"
    },
    "dateAdded": "2022/03/01"
  },
  {
    "name": "Dave",
    "email": "dave@example.com",
    "avatar": "https://loremflickr.com/200/200",
    "certificationLink": "https://www.credly.com/organizations/devstream/badge",
    "badge": {
      "type": "Evangelist",
      "achievement": "Associate"
    },
    "dateAdded": "2022/03/01"
  },
  {
    "name": "Elf",
    "email": "elf@example.com",
    "avatar": "https://loremflickr.com/200/200",
    "certificationLink": "https://www.credly.com/organizations/devstream/badge",
    "badge": {
      "type": "Evangelist",
      "achievement": "Associate"
    },
    "dateAdded": "2022/03/01"
  },
  {
    "name": "Frank",
    "email": "frank@example.com",
    "avatar": "https://loremflickr.com/200/200",
    "certificationLink": "https://www.credly.com/organizations/devstream/badge",
    "badge": {
      "type": "Evangelist",
      "achievement": "Associate"
    },
    "dateAdded": "2022/03/01"
  },
  {
    "name": "Gerald",
    "email": "gerald@example.com",
    "avatar": "https://loremflickr.com/200/200",
    "certificationLink": "https://www.credly.com/organizations/devstream/badge",
    "badge": {
      "type": "Open-Source Contributor",
      "achievement": "Associate"
    },
    "dateAdded": "2022/03/01"
  }
]
